# CN-Celeb eval 전용 config. run_test.py로 사용.
# checkpoint는 save_dir 아래 checkpoints/ 에 있어야 함.
# save_dir을 본인 실험 디렉터리로 수정 (예: outputs/supcon, outputs/ncu-xxx)
trainer:
  devices: 1
  accelerator: gpu
  logger:
    - class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
      init_args:
        save_dir: outputs/ncu-Softloss-alpha0.5-30ep-resnet34 #outputs/supcon_resnet34   # checkpoint 위치 - 본인 실험 dir로 변경
        name: null
        version: ""
model:
  class_path: trainers.SupConTrainer
  init_args:
    loss_func:
      class_path: losses.SupConLoss
      init_args:
        temperature: 0.1
        learn_temperature: True
        margin: 0.0
    # encoder:
    #   class_path: models.ECAPAEncoder
    #   init_args:
    #     input_size: 80
    #     channels: [256, 256, 256, 256, 768]
    #     kernel_sizes: [5, 3, 3, 3, 1]
    #     dilations: [1, 2, 3, 4, 1]
    #     attention_channels: 128
    #     lin_neurons: 192
    #     res2net_scale: 8
    #     se_channels: 128
    encoder:
      class_path: models.ResNetEncoder
      init_args:
        layers: [3, 4, 6, 3]  # ThinResnet34 구조
        num_filters: [16, 32, 64, 128]
        nOut: 192
        encoder_type: SAP  
    projector:
      class_path: models.IdentityProjector
    clustering_model:
      class_path: sklearn.cluster.KMeans
      init_args:
        n_clusters: 50
        random_state: 0
        n_init: 5
    learning_rate: 0.01
    optim_weight_decay: 2e-06
    lr_scheduler_type: cosine
    sample_rate: 16000
    samples_per_epoch: 1000000
    batch_size: 600
data:
  class_path: data.VoxCelebSupConDataModule
  init_args:
    train_config:
      data_dir: /home/sooyoung/interspeech/dev/aac
      spk2utt_file_path: /home/sooyoung/interspeech/dev/aac/spk2utt
      wav_processor: torch.nn.Identity
      feature_extractor:
        class_path: data.feature_extractors.SBFbank
        init_args:
          sample_rate: 16000
          f_min: 0
          f_max: 8000
          n_fft: 400
          n_mels: 80
          win_length: 400
          hop_length: 160
          postprocessor: data.augmentations.SpecNormalization
      sample_rate: 16_000
      segment_length: 48_000
      samples_per_epoch: 1_000_000
      batch_size: 600
      num_workers: 8
    valid_config:
      data_dir: /home/sooyoung/interspeech/CN-Celeb_flac/eval
      trials_file_path: /home/sooyoung/interspeech/chns/resources/cnceleb_eval_pairs.txt
      feature_extractor: ${data.init_args.train_config.feature_extractor}
      sample_rate: 16000
      segment_length: null
      batch_size: 1
      num_workers: 8
    test_config:
      data_dir: /home/sooyoung/interspeech/CN-Celeb_flac/eval
      trials_file_path: /home/sooyoung/interspeech/chns/resources/cnceleb_eval_pairs.txt
      feature_extractor: ${data.init_args.train_config.feature_extractor}
      sample_rate: 16000
      segment_length: null
      batch_size: 1
      num_workers: 8
    clustering_config: null
    use_unique_batch_sampler: False
